-- ============================================================
-- 01_schema.sql  (auto-generated by gen_mock.py)
-- Local StarRocks schema — mirrors Starrock_Schema.txt
-- S3 paths point to MinIO bucket: s3://warehouse/
-- ============================================================

-- ── Raw / Bronze (Hive catalog → MinIO) ───────────────────────────────────────
CREATE DATABASE IF NOT EXISTS sdp_dev_hive_catalog.sdp_raw;

CREATE TABLE IF NOT EXISTS sdp_dev_hive_catalog.sdp_raw.raw_dmp_public_asset (
  `id` varchar(65533), `created_time` bigint, `additional_info` varchar(65533),
  `customer_id` varchar(65533), `asset_profile_id` varchar(65533),
  `name` varchar(65533), `label` varchar(65533), `tenant_id` varchar(65533),
  `type` varchar(65533), `external_id` varchar(65533), `version` bigint,
  `processing_day` varchar(65533)
) PROPERTIES ("location" = "s3://warehouse/raw/db/dmp/public.asset/");

CREATE TABLE IF NOT EXISTS sdp_dev_hive_catalog.sdp_raw.raw_dmp_public_asset_profile (
  `id` varchar(65533), `created_time` bigint, `name` varchar(65533),
  `image` varchar(65533), `description` varchar(65533), `is_default` boolean,
  `tenant_id` varchar(65533), `default_rule_chain_id` varchar(65533),
  `default_dashboard_id` varchar(65533), `default_queue_name` varchar(65533),
  `default_edge_rule_chain_id` varchar(65533), `external_id` varchar(65533),
  `version` bigint, `processing_day` varchar(65533)
) PROPERTIES ("location" = "s3://warehouse/raw/db/dmp/public.asset_profile/");

CREATE TABLE IF NOT EXISTS sdp_dev_hive_catalog.sdp_raw.raw_dmp_public_device (
  `id` varchar(65533), `created_time` bigint, `additional_info` varchar(65533),
  `customer_id` varchar(65533), `device_profile_id` varchar(65533),
  `device_data` varchar(65533), `type` varchar(65533), `name` varchar(65533),
  `label` varchar(65533), `tenant_id` varchar(65533), `firmware_id` varchar(65533),
  `software_id` varchar(65533), `external_id` varchar(65533), `version` bigint,
  `processing_day` varchar(65533)
) PROPERTIES ("location" = "s3://warehouse/raw/db/dmp/public.device/");

CREATE TABLE IF NOT EXISTS sdp_dev_hive_catalog.sdp_raw.raw_dmp_public_device_profile (
  `id` varchar(65533), `created_time` bigint, `name` varchar(65533),
  `type` varchar(65533), `image` varchar(65533), `transport_type` varchar(65533),
  `provision_type` varchar(65533), `profile_data` varchar(65533),
  `description` varchar(65533), `is_default` boolean, `tenant_id` varchar(65533),
  `firmware_id` varchar(65533), `software_id` varchar(65533),
  `default_rule_chain_id` varchar(65533), `default_dashboard_id` varchar(65533),
  `default_queue_name` varchar(65533), `provision_device_key` varchar(65533),
  `default_edge_rule_chain_id` varchar(65533), `external_id` varchar(65533),
  `version` bigint, `processing_day` varchar(65533)
) PROPERTIES ("location" = "s3://warehouse/raw/db/dmp/public.device_profile/");

CREATE TABLE IF NOT EXISTS sdp_dev_hive_catalog.sdp_raw.raw_dmp_public_relation (
  `from_id` varchar(65533), `from_type` varchar(65533), `to_id` varchar(65533),
  `to_type` varchar(65533), `relation_type_group` varchar(65533),
  `relation_type` varchar(65533), `additional_info` varchar(65533),
  `version` bigint, `processing_day` varchar(65533)
) PROPERTIES ("location" = "s3://warehouse/raw/db/dmp/public.relation/");

CREATE TABLE IF NOT EXISTS sdp_dev_hive_catalog.sdp_raw.raw_parking_db_vehicle_histories (
  `id` varchar(65533), `card_number` varchar(65533), `lpn` varchar(65533),
  `lpn_cmp` varchar(65533), `lpn_camera_in` varchar(65533), `lpn_in_edited` varchar(65533),
  `lpn_camera_out` varchar(65533), `lpn_out_edited` varchar(65533),
  `service_id` varchar(65533), `service_name` varchar(65533),
  `owner_customer_id` varchar(65533), `org_unit_code` varchar(65533),
  `org_unit_name` varchar(65533), `pk_lot_id` varchar(65533), `pk_lot_name` varchar(65533),
  `entry_point_in_id` varchar(65533), `entry_point_in_name` varchar(65533),
  `lane_in_id` varchar(65533), `lane_in_name` varchar(65533),
  `entry_point_out_id` varchar(65533), `entry_point_out_name` varchar(65533),
  `lane_out_id` varchar(65533), `lane_out_name` varchar(65533),
  `direction_type` varchar(65533), `check_in_at` varchar(65533), `check_out_at` varchar(65533),
  `payment_type` varchar(65533), `use_voucher` boolean,
  `wallet_balance_before` bigint, `wallet_balance_after` bigint, `total_topup` bigint,
  `bank_transfer` bigint, `parking_fee` bigint, `lost_card_fee` bigint,
  `promotion_amount` bigint, `promotion_vinfast_amount` bigint, `amount_due` bigint,
  `used_change` bigint, `open_mode_in` varchar(65533), `open_mode_out` varchar(65533),
  `check_in_lane_image_id` varchar(65533), `check_out_lane_image_id` varchar(65533),
  `history_state` varchar(65533), `description` varchar(65533), `area_id` varchar(65533),
  `computer_inid` varchar(65533), `computer_outid` varchar(65533),
  `haunt_id` varchar(65533), `haunt_name` varchar(65533), `vehicle_type` varchar(65533),
  `park_duration` bigint, `has_manual_edits` boolean, `service_category` varchar(65533),
  `check_in_note` varchar(65533), `check_out_note` varchar(65533), `is_exception` boolean,
  `created_by_user_id` varchar(65533), `created_by_username` varchar(65533),
  `last_modified_by_user_id` varchar(65533), `last_modified_by_username` varchar(65533),
  `created_at` varchar(65533), `last_modified_at` varchar(65533),
  `face_id_in` varchar(65533), `face_id_out` varchar(65533),
  `feature_vector_in` varchar(65533), `feature_vector_out` varchar(65533),
  `checkin_customer_id` varchar(65533), `checkout_customer_id` varchar(65533),
  `processing_day` varchar(65533)
) PROPERTIES ("location" = "s3://warehouse/raw/db/parking-couchbase/vehicle_histories/");

-- ── Staging / Silver (Iceberg catalog → MinIO) ────────────────────────────────
CREATE DATABASE IF NOT EXISTS sdp_dev_iceberg_catalog.sdp_staging;

CREATE TABLE IF NOT EXISTS sdp_dev_iceberg_catalog.sdp_staging.stg_dmp_asset_profiles (
  `asset_profile_id` varchar(65533), `name` varchar(65533), `image` varchar(65533),
  `description` varchar(65533), `is_default` boolean, `tenant_id` varchar(65533),
  `default_rule_chain_id` varchar(65533), `default_dashboard_id` varchar(65533),
  `default_queue_name` varchar(65533), `default_edge_rule_chain_id` varchar(65533),
  `external_id` varchar(65533), `version` bigint, `processing_day` date,
  `created_at` datetime, `_dbt_loaded_at` datetime
) PROPERTIES ("location" = "s3://warehouse/staging/stg_dmp_asset_profiles/");

CREATE TABLE IF NOT EXISTS sdp_dev_iceberg_catalog.sdp_staging.stg_dmp_assets (
  `asset_id` varchar(65533), `additional_info` varchar(65533), `customer_id` varchar(65533),
  `asset_profile_id` varchar(65533), `name` varchar(65533), `label` varchar(65533),
  `tenant_id` varchar(65533), `type` varchar(65533), `external_id` varchar(65533),
  `version` bigint, `processing_day` date, `created_at` datetime, `_dbt_loaded_at` datetime
) PROPERTIES ("location" = "s3://warehouse/staging/stg_dmp_assets/");

CREATE TABLE IF NOT EXISTS sdp_dev_iceberg_catalog.sdp_staging.stg_dmp_device_profiles (
  `device_profile_id` varchar(65533), `name` varchar(65533), `type` varchar(65533),
  `image` varchar(65533), `transport_type` varchar(65533), `provision_type` varchar(65533),
  `profile_data` varchar(65533), `description` varchar(65533), `is_default` boolean,
  `tenant_id` varchar(65533), `firmware_id` varchar(65533), `software_id` varchar(65533),
  `default_rule_chain_id` varchar(65533), `default_dashboard_id` varchar(65533),
  `default_queue_name` varchar(65533), `provision_device_key` varchar(65533),
  `default_edge_rule_chain_id` varchar(65533), `external_id` varchar(65533),
  `version` bigint, `processing_day` date, `created_at` datetime, `_dbt_loaded_at` datetime
) PROPERTIES ("location" = "s3://warehouse/staging/stg_dmp_device_profiles/");

CREATE TABLE IF NOT EXISTS sdp_dev_iceberg_catalog.sdp_staging.stg_dmp_device_status_events (
  `event_id` varchar(65533), `device_id` varchar(65533), `tenant_id` varchar(65533),
  `event_type` varchar(65533), `source_system` varchar(65533), `device_code` varchar(65533),
  `device_type` varchar(65533), `ip_address` varchar(65533), `current_status` varchar(65533),
  `previous_status` varchar(65533), `status_change_reason` varchar(65533),
  `event_time` datetime, `event_date` date, `event_hour` datetime,
  `processing_day` date, `is_online` boolean, `is_status_change_event` boolean,
  `_dbt_loaded_at` datetime
) PROPERTIES ("location" = "s3://warehouse/staging/stg_dmp_device_status_events/");

CREATE TABLE IF NOT EXISTS sdp_dev_iceberg_catalog.sdp_staging.stg_dmp_devices (
  `device_id` varchar(65533), `additional_info` varchar(65533), `customer_id` varchar(65533),
  `device_profile_id` varchar(65533), `device_data` varchar(65533), `type` varchar(65533),
  `name` varchar(65533), `label` varchar(65533), `tenant_id` varchar(65533),
  `firmware_id` varchar(65533), `software_id` varchar(65533), `external_id` varchar(65533),
  `version` bigint, `processing_day` date, `created_at` datetime, `_dbt_loaded_at` datetime
) PROPERTIES ("location" = "s3://warehouse/staging/stg_dmp_devices/");

CREATE TABLE IF NOT EXISTS sdp_dev_iceberg_catalog.sdp_staging.stg_dmp_evt_connectivity (
  `msgtype` varchar(65533), `deviceid` varchar(65533), `tenantid` varchar(65533),
  `customerid` varchar(65533), `devicecode` varchar(65533), `status` varchar(65533),
  `offlinereason` varchar(65533), `qualityscore` int, `icmpreachable` varchar(65533),
  `ts` bigint, `processing_day` varchar(65533)
) PROPERTIES ("location" = "s3://warehouse/staging/stg_dmp_evt_connectivity/");

CREATE TABLE IF NOT EXISTS sdp_dev_iceberg_catalog.sdp_staging.stg_dmp_relations (
  `from_id` varchar(65533), `from_type` varchar(65533), `to_id` varchar(65533),
  `to_type` varchar(65533), `relation_type_group` varchar(65533),
  `relation_type` varchar(65533), `additional_info` varchar(65533),
  `version` bigint, `processing_day` date, `_dbt_loaded_at` datetime
) PROPERTIES ("location" = "s3://warehouse/staging/stg_dmp_relations/");

CREATE TABLE IF NOT EXISTS sdp_dev_iceberg_catalog.sdp_staging.stg_vehicle_histories (
  `event_id` varchar(65533), `card_number` varchar(65533), `lpn` varchar(65533),
  `lpn_cmp` varchar(65533), `lpn_camera_in` varchar(65533), `lpn_in_edited` varchar(65533),
  `lpn_camera_out` varchar(65533), `lpn_out_edited` varchar(65533),
  `service_id` varchar(65533), `service_name` varchar(65533),
  `owner_customer_id` varchar(65533), `org_unit_code` varchar(65533),
  `org_unit_name` varchar(65533), `pk_lot_id` varchar(65533), `pk_lot_name` varchar(65533),
  `entry_point_in_id` varchar(65533), `entry_point_in_name` varchar(65533),
  `lane_in_id` varchar(65533), `lane_in_name` varchar(65533),
  `entry_point_out_id` varchar(65533), `entry_point_out_name` varchar(65533),
  `lane_out_id` varchar(65533), `lane_out_name` varchar(65533),
  `direction_type` varchar(65533), `check_in_at_raw` varchar(65533),
  `check_out_at_raw` varchar(65533), `check_in_at` datetime, `check_out_at` datetime,
  `payment_type` varchar(65533), `use_voucher` varchar(65533),
  `wallet_balance_before_raw` varchar(65533), `wallet_balance_after_raw` varchar(65533),
  `total_topup_raw` varchar(65533), `bank_transfer_raw` varchar(65533),
  `parking_fee_raw` varchar(65533), `lost_card_fee_raw` varchar(65533),
  `promotion_amount_raw` varchar(65533), `promotion_vinfast_amount_raw` varchar(65533),
  `amount_due_raw` varchar(65533), `used_change_raw` varchar(65533),
  `open_mode_in` varchar(65533), `open_mode_out` varchar(65533),
  `check_in_lane_image_id` varchar(65533), `check_out_lane_image_id` varchar(65533),
  `history_state` varchar(65533), `description` varchar(65533), `area_id` varchar(65533),
  `computer_inid` varchar(65533), `computer_outid` varchar(65533),
  `haunt_id` varchar(65533), `haunt_name` varchar(65533), `vehicle_type` varchar(65533),
  `park_duration_ms` bigint, `has_manual_edits` varchar(65533),
  `service_category` varchar(65533), `check_in_note` varchar(65533),
  `check_out_note` varchar(65533), `is_exception` varchar(65533),
  `created_by_user_id` varchar(65533), `created_by_username` varchar(65533),
  `last_modified_by_user_id` varchar(65533), `last_modified_by_username` varchar(65533),
  `created_at` datetime, `last_modified_at` datetime,
  `face_id_in` varchar(65533), `face_id_out` varchar(65533),
  `feature_vector_in` varchar(65533), `feature_vector_out` varchar(65533),
  `checkin_customer_id` varchar(65533), `checkout_customer_id` varchar(65533),
  `event_date` date, `_dbt_loaded_at` datetime
) PROPERTIES ("location" = "s3://warehouse/staging/stg_vehicle_histories/");

-- ── Golden (Iceberg catalog → MinIO) ──────────────────────────────────────────
CREATE DATABASE IF NOT EXISTS sdp_dev_iceberg_catalog.sdp_golden;

CREATE TABLE IF NOT EXISTS sdp_dev_iceberg_catalog.sdp_golden.dim_asset (
  `asset_sk` varchar(65533), `asset_id` varchar(65533), `asset_name` varchar(65533),
  `asset_label` varchar(65533), `asset_type` varchar(65533), `additional_info` varchar(65533),
  `customer_id` varchar(65533), `tenant_id` varchar(65533), `external_id` varchar(65533),
  `asset_profile_id` varchar(65533), `asset_profile_name` varchar(65533),
  `asset_profile_description` varchar(65533), `asset_profile_is_default` boolean,
  `default_rule_chain_id` varchar(65533), `default_dashboard_id` varchar(65533),
  `default_queue_name` varchar(65533), `default_edge_rule_chain_id` varchar(65533),
  `created_at` datetime, `_dbt_loaded_at` datetime
) PROPERTIES ("location" = "s3://warehouse/golden/dim_asset/");

CREATE TABLE IF NOT EXISTS sdp_dev_iceberg_catalog.sdp_golden.dim_asset_profile (
  `asset_profile_sk` varchar(65533), `asset_profile_id` varchar(65533),
  `asset_profile_name` varchar(65533), `asset_profile_description` varchar(65533),
  `is_default` boolean, `tenant_id` varchar(65533),
  `default_rule_chain_id` varchar(65533), `default_dashboard_id` varchar(65533),
  `default_queue_name` varchar(65533), `default_edge_rule_chain_id` varchar(65533),
  `image` varchar(65533), `created_at` datetime, `_dbt_loaded_at` datetime
) PROPERTIES ("location" = "s3://warehouse/golden/dim_asset_profile/");

CREATE TABLE IF NOT EXISTS sdp_dev_iceberg_catalog.sdp_golden.dim_date (
  `date_key` int, `full_date` date, `year` int, `quarter` int, `month` int, `day` int,
  `year_month` varchar(65533), `year_week` varchar(65533), `day_of_year` int,
  `day_of_week` int, `day_name` varchar(65533), `day_name_short` varchar(65533),
  `is_weekend` boolean, `month_name` varchar(65533), `month_name_short` varchar(65533)
) PROPERTIES ("location" = "s3://warehouse/golden/dim_date/");
