version: "3.9"

services:
  ibis-server:
    image: custom/wren-engine-ibis:local
    build:
      context: ../../wren-engine/ibis-server
      dockerfile: Dockerfile
      args:
        WHEEL_SOURCE: docker
      additional_contexts:
        wren-core-py: ../../wren-engine/wren-core-py
        wren-core: ../../wren-engine/wren-core
        wren-core-base: ../../wren-engine/wren-core-base
        mcp-server: ../../wren-engine/mcp-server
    ports:
      - "8000:8000"
    environment:
      WREN_ENGINE_ENDPOINT: http://host.docker.internal:8080
