import { useCallback, useEffect, useRef, useState } from 'react';
import { useMutation, useLazyQuery } from '@apollo/client';
import {
  GENERATE_RELATIONSHIP_RECOMMENDATIONS,
  GET_RELATIONSHIP_RECOMMENDATION_TASK,
} from '@/apollo/client/graphql/dataSource';
import type { RelationsDataType } from '@/components/table/ModelRelationSelectionTable';

type SelectedRecommendRelations = { [modelName: string]: RelationsDataType[] };

const POLL_INTERVAL_MS = 2000;

interface AIRelationship {
  name: string;
  fromModel: string;
  fromColumn: string;
  type: string;
  toModel: string;
  toColumn: string;
  reason: string;
  fromModelId: number;
  fromModelReferenceName: string;
  fromColumnId: number;
  fromColumnReferenceName: string;
  toModelId: number;
  toModelReferenceName: string;
  toColumnId: number;
  toColumnReferenceName: string;
}

function mapAIRelationshipToRelation(rel: AIRelationship) {
  return {
    name: rel.name,
    fromField: {
      modelId: String(rel.fromModelId),
      modelName: rel.fromModelReferenceName,
      fieldId: String(rel.fromColumnId),
      fieldName: rel.fromColumnReferenceName,
    },
    toField: {
      modelId: String(rel.toModelId),
      modelName: rel.toModelReferenceName,
      fieldId: String(rel.toColumnId),
      fieldName: rel.toColumnReferenceName,
    },
    type: rel.type as any,
    isAutoGenerated: true,
    reason: rel.reason,
    properties: {},
  };
}

export default function useAIRelationshipRecommendation(
  onMerge: (aiRelations: SelectedRecommendRelations) => void,
) {
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [elapsed, setElapsed] = useState(0);
  const taskIdRef = useRef<string | null>(null);
  const pollTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  const [generateMutation] = useMutation(GENERATE_RELATIONSHIP_RECOMMENDATIONS);
  const [pollTask] = useLazyQuery(GET_RELATIONSHIP_RECOMMENDATION_TASK, {
    fetchPolicy: 'no-cache',
  });

  const stopPolling = useCallback(() => {
    if (pollTimerRef.current) {
      clearTimeout(pollTimerRef.current);
      pollTimerRef.current = null;
    }
  }, []);

  const poll = useCallback(
    async (taskId: string) => {
      try {
        const { data } = await pollTask({ variables: { taskId } });
        const task = data?.relationshipRecommendationTask;

        if (!task) return;

        if (task.status === 'generating') {
          pollTimerRef.current = setTimeout(
            () => poll(taskId),
            POLL_INTERVAL_MS,
          );
          return;
        }

        setGenerating(false);

        if (task.status === 'failed') {
          setError(task.error?.message || 'AI generation failed.');
          return;
        }

        if (task.status === 'finished' && task.relationships?.length) {
          const aiRelations: SelectedRecommendRelations = {};
          for (const rel of task.relationships as AIRelationship[]) {
            const modelKey = rel.fromModelReferenceName;
            if (!aiRelations[modelKey]) aiRelations[modelKey] = [];
            aiRelations[modelKey].push(mapAIRelationshipToRelation(rel));
          }
          onMerge(aiRelations);
        }
      } catch (err: any) {
        setGenerating(false);
        setError(err?.message || 'Failed to get AI recommendation result.');
      }
    },
    [pollTask, onMerge],
  );

  const generate = useCallback(async () => {
    setError(null);
    setElapsed(0);
    setGenerating(true);
    try {
      const { data } = await generateMutation();
      const taskId = data?.generateRelationshipRecommendations?.id;
      if (!taskId) throw new Error('No task ID returned from AI service.');
      taskIdRef.current = taskId;
      pollTimerRef.current = setTimeout(() => poll(taskId), POLL_INTERVAL_MS);
    } catch (err: any) {
      setGenerating(false);
      setError(err?.message || 'Failed to start AI recommendation.');
    }
  }, [generateMutation, poll]);

  useEffect(() => {
    return () => stopPolling();
  }, [stopPolling]);

  // tick the elapsed-seconds counter while generating
  useEffect(() => {
    if (!generating) return;
    const timer = setInterval(() => setElapsed((prev) => prev + 1), 1000);
    return () => clearInterval(timer);
  }, [generating]);

  return { generating, error, elapsed, generate };
}
